### ISSUE TITLE
RED.util.evaluateJSONataExpression must include a callback with Node-RED 4.0

### ISSUE THREAD

**Issue by bachph** [Autexis-IT/node-red-contrib-payload-logger#8]
While using your node I get a lot of errors in the debug messages:

`"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."`

**Comment by atx-dgr** [comment]
Hi bachph

Thank you for your issue. We will take care of it during the next few days.

**Comment by atx-dgr** [comment]
Hi @bachph
We released version 1.2.0, which includes the fix for your issue.
